apiVersion: v1
kind: Service
metadata:
  name: customer-datagrid-backend-service
spec:
  selector:
    app: customer-datagrid-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
